name: Cypress Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install dependencies with caching
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Cypress binary
        run: pnpm exec cypress install

      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7
        env:
          APP_URL: "http://localhost:3000"
          NEXT_PUBLIC_API_BASE_URL: "https://ignite-devstore-api.vercel.app"
        with:
          install: false
          build: pnpm run build
          start: pnpm start
